# Generated by Django 5.1.6 on 2025-11-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('code', models.CharField(blank=True, max_length=8, unique=True)),
                ('expire_days', models.PositiveIntegerField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ma'lumot ",
                'verbose_name_plural': "Ma'lumotlar",
            },
        ),
    ]
